//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid EmployeeId { get; set; }
        public string NIP { get; set; }
        public string FullName { get; set; }
        public string Department { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
