//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid MessageId { get; set; }
        public Nullable<System.Guid> Sender { get; set; }
        public Nullable<System.DateTime> Sent { get; set; }
        public Nullable<System.DateTime> Received { get; set; }
        public Nullable<System.Guid> RecipientUser { get; set; }
        public Nullable<System.Guid> RecipientTeam { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> Expired { get; set; }
        public Nullable<int> StatusCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
