//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public System.Guid NewsId { get; set; }
        public string Author { get; set; }
        public System.DateTime PublishedOn { get; set; }
        public int Category { get; set; }
        public string Title { get; set; }
        public string NewsContent { get; set; }
        public int StatusCode { get; set; }
        public byte[] NewsImage { get; set; }
    }
}
