//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinBoard
    {
        public System.Guid PinBoardId { get; set; }
        public Nullable<System.Guid> TeamId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.Guid> AssigneeId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> StatusCode { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
