//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StringMap
    {
        public System.Guid StringmapId { get; set; }
        public string Entity { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> AttributeValue { get; set; }
        public string Value { get; set; }
    }
}
