//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public System.Guid TeamMemberId { get; set; }
        public Nullable<System.Guid> TeamId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
