//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.PinBoards = new HashSet<PinBoard>();
            this.TeamMembers = new HashSet<TeamMember>();
            this.Messages = new HashSet<Message>();
        }
    
        public System.Guid TeamId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Avatar { get; set; }
        public Nullable<int> StatusCode { get; set; }
    
        public virtual ICollection<PinBoard> PinBoards { get; set; }
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
