//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhizzleAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Connections = new HashSet<Connection>();
            this.Connections1 = new HashSet<Connection>();
            this.PinBoards = new HashSet<PinBoard>();
            this.TeamMembers = new HashSet<TeamMember>();
            this.UserActivities = new HashSet<UserActivity>();
            this.Messages = new HashSet<Message>();
            this.PinBoards1 = new HashSet<PinBoard>();
        }
    
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string IMEI { get; set; }
        public byte[] Avatar { get; set; }
        public string Status { get; set; }
        public Nullable<bool> ShareLocation { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> LocationDate { get; set; }
        public Nullable<int> StatusCode { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Connection> Connections { get; set; }
        public virtual ICollection<Connection> Connections1 { get; set; }
        public virtual PinBoard PinBoard { get; set; }
        public virtual ICollection<PinBoard> PinBoards { get; set; }
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        public virtual ICollection<UserActivity> UserActivities { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<PinBoard> PinBoards1 { get; set; }
    }
}
